### ISSUE TITLE
CSS class `.mozilla-only` does not work with Thunderbird

### ISSUE THREAD

**Issue by tdulcet** [TinyWebEx/AutomaticSettings#11]
This line does not work in Thunderbird: https://github.com/TinyWebEx/AutomaticSettings/blob/f62226d8f960e600439f4e6bd992977d17323425/EnvironmentalOptions.js#L38

since the vendor name is blank: 
![image](https://user-images.githubusercontent.com/15305150/112818434-60b56100-9038-11eb-8392-4531d12cb44b.png)

I tested it with both Thunderbird 78.9 ESR and 88 Beta. We should either submit a bug to them on BMO or change that line to use [the name instead](https://github.com/rugk/unicodify/pull/17#discussion_r586307625).

This is currently blocking Thunderbird support for Unicodify, although context menu support is also blocked by [bug 1656506](https://bugzilla.mozilla.org/show_bug.cgi?id=1656506).

Originally posted in https://github.com/rugk/unicodify/pull/17#discussion_r603154896.

**Comment by rugk** [comment]
Oh nooo… uhm…

> We should either submit a bug to them on BMO or change that line to use the name instead.

We should definitively submit a bug, given it clearly is a bug…

However, if you'd need it, I'd be fine with a workaround like this:
```Js
// Thunderbird is explicitly checked as a workaround as Thunderbird does not return the vendor correctly <bug link>
return browserInfo.vendor === "Mozilla" || browserInfo.name === "Thunderbird"; 
```

**Comment by tdulcet** [comment]
> We should definitively submit a bug, given it clearly is a bug…

OK, I just created [bug 1702722](https://bugzilla.mozilla.org/show_bug.cgi?id=1702722). Note that the `getBrowserInfo()` function is currently [only available in Firefox/Thunderbird](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getBrowserInfo#browser_compatibility), so both the `isMozilla()` and `isFirefox()` functions will fail in Chrome.

> However, if you'd need it, I'd be fine with a workaround like this

OK, that should work for Unicodify in the meantime...
