### ISSUE TITLE
Options page does not work with Chrome/Chromium

### ISSUE THREAD

**Issue by tdulcet** [TinyWebEx/AutomaticSettings#12]
This code block does not work in Chrome/Chromium: https://github.com/TinyWebEx/AutomaticSettings/blob/26c51c6ac40171731f11ec4855a93c591811e301/internal/LoadAndSave.js#L167-L178

It causes all the settings to be identified as managed, which effectively disables the options page:
![image](https://user-images.githubusercontent.com/15305150/95012823-79483f80-05f0-11eb-8d4d-14338308ca21.png)

This is currently blocking Chrome support for the Awesome Emoji Picker and Unicodify. It is also blocking me from using this library in several other extensions I am developing, like [Colab Autorun and Connect](https://github.com/tdulcet/Colab-Autorun-and-Connect).

Originally posted in https://github.com/rugk/awesome-emoji-picker/issues/4#issuecomment-703043742.

**Comment by rugk** [comment]
And I vaguely remember there was some Promise one should comment that would fix that bug. Did not you say something like that?

Anyway, thanks for reporting it here, which is certainly the appropriate place.

**Comment by tdulcet** [comment]
> And I vaguely remember there was some Promise one should comment that would fix that bug. Did not you say something like that?

Yes, in https://github.com/rugk/awesome-emoji-picker/issues/4#issuecomment-703043742. I said that developers can replace the above block with `return Promise.reject();`, which will make the options page work, but obviously disable the managed options feature.

**Comment by rugk** [comment]
So… let's better find the real issue and the real solution for that, don't we?

**Comment by tdulcet** [comment]
I investigated it several months ago and I believe the issue was that Firefox rejects the promise when a managed option is not found, but Chrome resolves it in that case, although just with an empty object...

**Comment by rugk** [comment]
Okay, then theoretically, https://github.com/TinyWebEx/AutomaticSettings/issues/12 should fix the issue then (untested).

**Comment by tdulcet** [comment]
Yes, that works great! Thanks for fixing it. 👍

As expected, I do get some errors in the console, but they are probably better fixed with #11: 
![image](https://user-images.githubusercontent.com/15305150/113502347-ba0e0c00-94e0-11eb-8bce-5e0f43c665c7.png)

Also, the Unicodify options page is very skinny (compared to the Awesome Emoji Picker above), but it probably just needs some CSS : 
![image](https://user-images.githubusercontent.com/15305150/113502500-7ec00d00-94e1-11eb-9e61-bc6f57628afe.png)

**Comment by rugk** [comment]
Yeah, also that annoying wrap for helper texts becomes apparent there.
I've opened #17 now for that, as I just saw it was not tracked anywhere.
