### ISSUE TITLE
getBrowserInfo() errors in Chrome/Chromium

### ISSUE THREAD

**Issue by tdulcet** [TinyWebEx/AutomaticSettings#18]
Continuation of #11 and #12. See https://github.com/TinyWebEx/AutomaticSettings/issues/12#issuecomment-812993836:
> As expected, I do get some errors in the console, but they are probably better fixed with #11:
> ![image](https://user-images.githubusercontent.com/15305150/113502347-ba0e0c00-94e0-11eb-8bce-5e0f43c665c7.png)

I believe we will need to implement something similar to this: https://github.com/rugk/unicodify/pull/23#discussion_r618161272.

**Comment by rugk** [comment]
Okay, so IMHO the polyfill should handle this.

WOuld you mind to create an issue at https://github.com/mozilla/webextension-polyfill/?
Ah okay no, it does not do this: https://github.com/mozilla/webextension-polyfill/issues/116

**Comment by rugk** [comment]
Okay, fixed it.

I did some crazy thing and decided to use the (long-upon a time written and nearly forgotten) tests for that…
https://github.com/TinyWebEx/AutomaticSettings/pull/19

I know the tests are ugly and running them is a pain and I would not do so nowadays likely, but uff… let's ignore that.
